
package clientSoap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CatalogFacadeRemoteWSSoap", targetNamespace = "http://ejb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CatalogFacadeRemoteWSSoap {


    /**
     * 
     * @param arg0
     * @return
     *     returns clientSoap.DriverTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showDriver", targetNamespace = "http://ejb/", className = "clientSoap.ShowDriver")
    @ResponseWrapper(localName = "showDriverResponse", targetNamespace = "http://ejb/", className = "clientSoap.ShowDriverResponse")
    public DriverTO showDriver(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeDriver", targetNamespace = "http://ejb/", className = "clientSoap.RemoveDriver")
    @ResponseWrapper(localName = "removeDriverResponse", targetNamespace = "http://ejb/", className = "clientSoap.RemoveDriverResponse")
    public void removeDriver(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clientSoap.CarTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCarsByDriver", targetNamespace = "http://ejb/", className = "clientSoap.ListCarsByDriver")
    @ResponseWrapper(localName = "listCarsByDriverResponse", targetNamespace = "http://ejb/", className = "clientSoap.ListCarsByDriverResponse")
    public List<CarTO> listCarsByDriver(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<clientSoap.DriverTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllDrivers", targetNamespace = "http://ejb/", className = "clientSoap.ListAllDrivers")
    @ResponseWrapper(localName = "listAllDriversResponse", targetNamespace = "http://ejb/", className = "clientSoap.ListAllDriversResponse")
    public List<DriverTO> listAllDrivers();

    /**
     * 
     * @param arg0
     * @return
     *     returns clientSoap.CarTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showCar", targetNamespace = "http://ejb/", className = "clientSoap.ShowCar")
    @ResponseWrapper(localName = "showCarResponse", targetNamespace = "http://ejb/", className = "clientSoap.ShowCarResponse")
    public CarTO showCar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertCar", targetNamespace = "http://ejb/", className = "clientSoap.InsertCar")
    @ResponseWrapper(localName = "insertCarResponse", targetNamespace = "http://ejb/", className = "clientSoap.InsertCarResponse")
    public void insertCar(
        @WebParam(name = "arg0", targetNamespace = "")
        CarTO arg0);

    /**
     * 
     * @return
     *     returns clientSoap.CarTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastCarIndex", targetNamespace = "http://ejb/", className = "clientSoap.GetLastCarIndex")
    @ResponseWrapper(localName = "getLastCarIndexResponse", targetNamespace = "http://ejb/", className = "clientSoap.GetLastCarIndexResponse")
    public CarTO getLastCarIndex();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeCar", targetNamespace = "http://ejb/", className = "clientSoap.RemoveCar")
    @ResponseWrapper(localName = "removeCarResponse", targetNamespace = "http://ejb/", className = "clientSoap.RemoveCarResponse")
    public void removeCar(
        @WebParam(name = "arg0", targetNamespace = "")
        CarTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertDriver", targetNamespace = "http://ejb/", className = "clientSoap.InsertDriver")
    @ResponseWrapper(localName = "insertDriverResponse", targetNamespace = "http://ejb/", className = "clientSoap.InsertDriverResponse")
    public void insertDriver(
        @WebParam(name = "arg0", targetNamespace = "")
        DriverTO arg0);

    /**
     * 
     * @return
     *     returns java.util.List<clientSoap.CarTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllCars", targetNamespace = "http://ejb/", className = "clientSoap.ListAllCars")
    @ResponseWrapper(localName = "listAllCarsResponse", targetNamespace = "http://ejb/", className = "clientSoap.ListAllCarsResponse")
    public List<CarTO> listAllCars();

}
